// GENERATED by scripts/build-recipe-pool.mjs from server/data/recipes.ndjson.
// Do not edit by hand; run `npm run prep:recipes` to regenerate.

export interface PoolRecipe {
  id: string;
  title: string;
  nodes: number[];
}

export const RECIPE_POOL: PoolRecipe[] = [
  {
    "id": "seed-0000",
    "title": "Classic Margherita Pizza",
    "nodes": [
      113,
      623,
      1053,
      1120,
      1405,
      1644,
      1774
    ]
  },
  {
    "id": "seed-0001",
    "title": "Spaghetti Carbonara",
    "nodes": [
      84,
      153,
      543,
      669,
      1159,
      1166
    ]
  },
  {
    "id": "seed-0002",
    "title": "Chicken Tikka Masala",
    "nodes": [
      321,
      412,
      445,
      475,
      669,
      679,
      1122,
      1157,
      1644,
      1778
    ]
  },
  {
    "id": "seed-0003",
    "title": "Guacamole",
    "nodes": [
      81,
      332,
      412,
      918,
      1122,
      1405,
      1644
    ]
  },
  {
    "id": "seed-0004",
    "title": "Beef Bourguignon",
    "nodes": [
      84,
      124,
      226,
      275,
      669,
      1070,
      1122,
      1340
    ]
  },
  {
    "id": "seed-0005",
    "title": "Pad Thai",
    "nodes": [
      543,
      609,
      669,
      918,
      1177,
      1351,
      1427,
      1478
    ]
  },
  {
    "id": "seed-0006",
    "title": "Caesar Salad",
    "nodes": [
      47,
      543,
      669,
      904,
      911,
      1120,
      1159
    ]
  },
  {
    "id": "seed-0007",
    "title": "French Onion Soup",
    "nodes": [
      124,
      194,
      226,
      308,
      1122,
      1633
    ]
  },
  {
    "id": "seed-0008",
    "title": "Ratatouille",
    "nodes": [
      113,
      128,
      552,
      669,
      1120,
      1122,
      1644,
      1788
    ]
  },
  {
    "id": "seed-0009",
    "title": "Chicken Noodle Soup",
    "nodes": [
      275,
      290,
      321,
      544,
      669,
      1122,
      1160
    ]
  },
  {
    "id": "seed-0010",
    "title": "Beef Tacos",
    "nodes": [
      124,
      308,
      332,
      412,
      918,
      1122,
      1644,
      1652
    ]
  },
  {
    "id": "seed-0011",
    "title": "Mushroom Risotto",
    "nodes": [
      226,
      669,
      1070,
      1122,
      1159,
      1347,
      1690,
      1742
    ]
  },
  {
    "id": "seed-0012",
    "title": "Greek Salad",
    "nodes": [
      472,
      592,
      1119,
      1120,
      1122,
      1128,
      1644
    ]
  },
  {
    "id": "seed-0013",
    "title": "Banana Bread",
    "nodes": [
      93,
      102,
      226,
      363,
      543,
      623,
      1561
    ]
  },
  {
    "id": "seed-0014",
    "title": "Pancakes",
    "nodes": [
      92,
      226,
      543,
      623,
      1014,
      1405,
      1561
    ]
  },
  {
    "id": "seed-0015",
    "title": "Thai Green Curry",
    "nodes": [
      113,
      321,
      387,
      552,
      609,
      669,
      679,
      918
    ]
  },
  {
    "id": "seed-0016",
    "title": "Hummus",
    "nodes": [
      324,
      475,
      669,
      904,
      1120,
      1597
    ]
  },
  {
    "id": "seed-0017",
    "title": "Shakshuka",
    "nodes": [
      128,
      475,
      543,
      669,
      1120,
      1122,
      1157,
      1644
    ]
  },
  {
    "id": "seed-0018",
    "title": "Beef Stir Fry",
    "nodes": [
      124,
      205,
      669,
      679,
      1347,
      1427,
      1455,
      1516
    ]
  },
  {
    "id": "seed-0019",
    "title": "Apple Pie",
    "nodes": [
      54,
      226,
      363,
      543,
      623,
      904,
      1561
    ]
  },
  {
    "id": "seed-0020",
    "title": "Minestrone Soup",
    "nodes": [
      118,
      275,
      290,
      669,
      1122,
      1159,
      1166,
      1644,
      1788
    ]
  },
  {
    "id": "seed-0021",
    "title": "Fish and Chips",
    "nodes": [
      392,
      543,
      623,
      904,
      1268,
      1405
    ]
  },
  {
    "id": "seed-0022",
    "title": "Chicken Fajitas",
    "nodes": [
      128,
      321,
      475,
      669,
      918,
      1122,
      1157,
      1652
    ]
  },
  {
    "id": "seed-0023",
    "title": "Lentil Soup",
    "nodes": [
      275,
      290,
      475,
      669,
      910,
      1120,
      1122,
      1644
    ]
  },
  {
    "id": "seed-0024",
    "title": "Caprese Salad",
    "nodes": [
      95,
      113,
      1053,
      1120,
      1405,
      1644
    ]
  },
  {
    "id": "seed-0025",
    "title": "Beef Chili",
    "nodes": [
      118,
      124,
      128,
      333,
      475,
      669,
      1122,
      1644
    ]
  },
  {
    "id": "seed-0026",
    "title": "Garlic Butter Shrimp",
    "nodes": [
      226,
      332,
      669,
      904,
      1160,
      1478
    ]
  },
  {
    "id": "seed-0027",
    "title": "Vegetable Fried Rice",
    "nodes": [
      275,
      543,
      669,
      1173,
      1347,
      1427,
      1455,
      1516
    ]
  },
  {
    "id": "seed-0028",
    "title": "Pesto Pasta",
    "nodes": [
      113,
      669,
      1120,
      1159,
      1166,
      1226
    ]
  },
  {
    "id": "seed-0029",
    "title": "Tomato Basil Soup",
    "nodes": [
      113,
      226,
      445,
      669,
      1122,
      1644,
      1690
    ]
  },
  {
    "id": "seed-0030",
    "title": "Chocolate Chip Cookies",
    "nodes": [
      93,
      226,
      348,
      543,
      623,
      1561,
      1682
    ]
  },
  {
    "id": "seed-0031",
    "title": "Eggplant Parmesan",
    "nodes": [
      113,
      543,
      552,
      669,
      1053,
      1120,
      1159,
      1644
    ]
  },
  {
    "id": "seed-0032",
    "title": "Korean Bibimbap",
    "nodes": [
      124,
      275,
      543,
      1070,
      1347,
      1427,
      1455,
      1516,
      1529
    ]
  },
  {
    "id": "seed-0033",
    "title": "Roast Chicken",
    "nodes": [
      226,
      321,
      669,
      904,
      1374,
      1405,
      1633
    ]
  },
  {
    "id": "seed-0034",
    "title": "Falafel",
    "nodes": [
      324,
      412,
      475,
      623,
      669,
      1122,
      1160
    ]
  },
  {
    "id": "seed-0035",
    "title": "Miso Soup",
    "nodes": [
      494,
      1028,
      1427,
      1450,
      1639
    ]
  },
  {
    "id": "seed-0036",
    "title": "Beef Wellington",
    "nodes": [
      124,
      226,
      543,
      623,
      1070,
      1276,
      1633
    ]
  },
  {
    "id": "seed-0037",
    "title": "Strawberry Smoothie",
    "nodes": [
      102,
      793,
      1014,
      1556,
      1778
    ]
  },
  {
    "id": "seed-0038",
    "title": "Chicken Caesar Wrap",
    "nodes": [
      321,
      669,
      904,
      911,
      1120,
      1159,
      1652
    ]
  },
  {
    "id": "seed-0039",
    "title": "Vegetable Curry",
    "nodes": [
      275,
      285,
      387,
      412,
      475,
      669,
      679,
      1122,
      1173,
      1268
    ]
  }
];
